### ISSUE TITLE
How to make QR code?

### ISSUE THREAD

**Issue by SlimeVRX** [LinkSoul-AI/Chinese-LLaVA#9]
Hello

I came across this beautifully designed QR code on your GitHub repository and I'm very intrigued by its intricate design. Could you please share some insights on how you created this QR code? 

Thank you for your time and assistance!

Best regards,

Tin Nguyen

![image](https://github.com/LinkSoul-AI/Chinese-LLaVA/assets/99313947/34a3e5a6-8c9a-4eb9-8970-3b732891fc2b)

**Comment by fanmurt** [comment]
There are a lot of QR code templates here: https://www.qrdream.com/u/template

![qr code](https://github.com/user-attachments/assets/84a588ff-a2c1-4a4d-9b38-0dd5b18f848a)

**Comment by SlimeVRX** [comment]
Many thanks!
